const wordsAll = [
  {
    id: "33198",
    english: "mother",
    transcription: "[mʌðə]",
    russian: "мама",
    tags: "Family",
    tags_json: '["Family"]',
  },
  {
    id: "33200",
    english: "aunt",
    transcription: "[ænt]",
    russian: "тётя",
    tags: "Family",
    tags_json: '["Family"]',
  },
  {
    id: "33208",
    english: "peace",
    transcription: "[piːs]",
    russian: "мир",
    tags: "World",
    tags_json: '["World"]',
  },
  {
    id: "33209",
    english: "overwhelming",
    transcription: "[əʊvərˈwelmɪŋ]",
    russian: "ошеломляющий",
    tags: "Adjective",
    tags_json: '["Adjective"]',
  },
  {
    id: "33211",
    english: "forecast",
    transcription: "[ˈfɔːrkæst]",
    russian: "прогноз",
    tags: "Weather",
    tags_json: '["Weather"]',
  },
  {
    id: "33229",
    english: "mosquito",
    transcription: "[məˈskiː.təʊ]",
    russian: "комар",
    tags: "Animals",
    tags_json: '["Animals"]',
  },
  {
    id: "33250",
    english: "tornado",
    transcription: "[tɔːˈneɪ.dəʊ]",
    russian: "торнадо",
    tags: "Weather",
    tags_json: '["Weather"]',
  },
  {
    id: "33317",
    english: "scrooge",
    transcription: "[skruːdʒ]",
    russian: "скряга",
    tags: "Noun",
    tags_json: '["Noun"]',
  },
  {
    id: "33367",
    english: "cat",
    transcription: "[cæt]",
    russian: "кот",
    tags: "Animals",
    tags_json: '["Animals"]',
  },
  {
    id: "33390",
    english: "hang out",
    transcription: "|ˈhæŋ ˈaʊt|",
    russian: "тусоваться",
    tags: "Verb",
    tags_json: '["Verb"]',
  },
  {
    id: "33393",
    english: "girl",
    transcription: "[ɡɜːrl]",
    russian: "девочка",
    tags: "Noun",
    tags_json: '["Noun"]',
  },
  {
    id: "33404",
    english: "curious",
    transcription: "[ ˈkjʊrɪəs ]",
    russian: "любопытный ",
    tags: "Adjective",
    tags_json: '["Adjective"]',
  },
  {
    id: "33406",
    english: "brother",
    transcription: "[brʌðə]",
    russian: "брат",
    tags: "Family",
    tags_json: '["Family"]',
  },
  {
    id: "33407",
    english: "wind",
    transcription: "[wɪnd]",
    russian: "ветер",
    tags: "Weather",
    tags_json: '["Weather"]',
  },
  {
    id: "33408",
    english: "rain",
    transcription: "[reɪn]",
    russian: "дождь",
    tags: "Weather",
    tags_json: '["Weather"]',
  },
  {
    id: "33409",
    english: "murky",
    transcription: "[mɜːki]",
    russian: "мрачный",
    tags: "Weather",
    tags_json: '["Weather"]',
  },
  {
    id: "33410",
    english: "red",
    transcription: "[rɛd]",
    russian: "красный",
    tags: "Colors",
    tags_json: '["Colors"]',
  },
  {
    id: "33411",
    english: "sister",
    transcription: "[sɪstə]",
    russian: "сестра",
    tags: "Family",
    tags_json: '["Family"]',
  },
];

export default wordsAll;
